spring:
  datasource:
    name: sysqueue
    url: jdbc:mysql://121.196.174.196:3306/projectDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:./mapper/*.xml